HubSpot/NioSmtpClient

src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

Makes sure the future returned by `SmtpSessionFactory.connect` is executed on the provided `ExecutorService`.
@axiak

Connect async

---

src/main/java/com/hubspot/smtp/TestApp.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java

Closes all channels created by the `SmtpSessionFactory` when its `close` method is called.
@axiak

Close channels when SmtpSessionFactory.close is called

---

pom.xml
src/main/java/com/hubspot/smtp/TestApp.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java
src/main/java/com/hubspot/smtp/messages/ByteBufMessageContent.java
src/main/java/com/hubspot/smtp/messages/DotStuffing.java
src/main/java/com/hubspot/smtp/messages/DotStuffingChunkedStream.java
src/main/java/com/hubspot/smtp/messages/InputStreamMessageContent.java
src/main/java/com/hubspot/smtp/messages/MessageContent.java
src/main/java/com/hubspot/smtp/messages/MessageContentEncoding.java
src/main/java/com/hubspot/smtp/messages/MessageTermination.java
src/main/java/com/hubspot/smtp/utils/ByteBufs.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java
src/test/java/com/hubspot/smtp/messages/ByteBufMessageContentTest.java
src/test/java/com/hubspot/smtp/messages/DotStuffingChunkedStreamTest.java
src/test/java/com/hubspot/smtp/messages/DotStuffingTest.java
src/test/java/com/hubspot/smtp/utils/ByteBufsTest.java

Adds an abstract class, `MessageContent` together with two concrete subclasses, `ByteBufMessageContent` and `InputStreamMessageContent` to encapsulate the data of a message.
Both subclasses support dot-stuffing and can ensure the message content ends with `CRLF` so the SMTP connection doesn't hang. `InputStreamMessageContent` uses chunking to ensure large messages are sent without consuming too much memory, and tracks newlines across chunks to perform dot-stuffing.
@axiak

Add MessageContent interfaces and initial implementations

---

src/main/java/com/hubspot/smtp/messages/DotStuffing.java
src/test/java/com/hubspot/smtp/messages/DotStuffingTest.java

We don't need to retain this buffer if we're returning it directly.
@axiak

Fix memory leak

---

pom.xml
src/main/java/com/hubspot/smtp/TestApp.java
src/main/java/com/hubspot/smtp/client/ChannelClosedException.java
src/main/java/com/hubspot/smtp/client/ErrorResponseException.java
src/main/java/com/hubspot/smtp/client/Initializer.java
src/main/java/com/hubspot/smtp/client/KeepAliveHandler.java
src/main/java/com/hubspot/smtp/client/ResponseHandler.java
src/main/java/com/hubspot/smtp/client/SmtpClientResponse.java
src/main/java/com/hubspot/smtp/client/SmtpException.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/client/SmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java
src/main/java/com/hubspot/smtp/utils/SmtpResponses.java
src/test/java/com/hubspot/smtp/client/KeepAliveHandlerTest.java
src/test/java/com/hubspot/smtp/client/ResponseHandlerTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java
src/test/java/com/hubspot/smtp/utils/SmtpResponsesTest.java

`KeepAliveHandler` extends `IdleStateHandler` to track when nothing has been sent or received for the duration defined by `SmtpSessionConfig::getKeepAliveTimeout`. If nothing has been sent/received, `KeepAliveHandler` sends a NOOP to the remote server and sets an `expectingNoopResponse` flag. `KeepAliveHandler` overrides `channelRead` to intercept responses and drops the first one it sees if `expectingNoopResponse` is set. This prevents `ResponseHandler` from logging a warning if it receives the NOOP response.
If we're waiting for a NOOP response when the timer fires, we don't send another. If we're waiting for a response to a non-NOOP command, we don't send a NOOP. If a request is sent while we're waiting for a NOOP response, we queue it and send when the NOOP response arrives. These …

Keep connections alive with NOOP

---

pom.xml
src/main/java/com/hubspot/smtp/TestApp.java
src/main/java/com/hubspot/smtp/client/Extension.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/client/SupportedExtensions.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

This PR introduces better parsing of the EHLO response and support for authenticating with the PLAIN or LOGIN mechanisms. 
Supported extensions are now parsed for you when EHLO returns, and exposed through the `isSupported` method on `SmtpSession`. The supported auth mechanisms are available through `isAuthPlainSupported` and `isAuthLoginSupported`.
If the EHLO response indicates an auth mechanism is supported, you can authenticate using `authPlain` or `authLogin`.
Because they might contain sensitive information we don't want in logs, a redacted version is included in the `debugString` sent to ResponseHandler
@axiak

Support auth plain and auth login

---

src/main/java/com/hubspot/smtp/client/EhloResponse.java
src/main/java/com/hubspot/smtp/client/MessageTooLargeException.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/EhloResponseTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

Parses the SIZE keyword of the EHLO response, and indicates if size is supported as well as the max size if that was included in the response. I also added an integration test to ensure we can send the max size with the MAIL command.
This PR also extracts EHLO parsing to its own class, and exposes the full response as a `Set<String>` for logging and detecting of extensions that aren't part of the `Extension` enum.
@axiak

Support the message size extension

---

src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/client/SmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

Makes it easy and efficient to execute callbacks on the event loop thread by passing `SmtpSessionConfig.DIRECT_EXECUTOR` when building the config.
Fixes https://github.com/HubSpot/NioSmtpClient/issues/7.
Note this isn't quite the same pattern as in [GRPC](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/ManagedChannelBuilder.java#L80-L91). Immutables doesn't (afaict) support having one builder method set the value of another property which is how GRPC [implements](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java#L164-L167) this. Having two values, e.g. `getDirectExecutor(boolean)` and `getExecutor(Executor)` makes it hard to know which value should take precedence, especially when constructing …

Direct executor

---

pom.xml
src/main/java/com/hubspot/smtp/client/Extension.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/test/java/com/hubspot/smtp/ChunkingExtension.java
src/test/java/com/hubspot/smtp/ExtensibleNettyServer.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/EhloResponseTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

Adds support for [SMTP chunking](https://tools.ietf.org/html/rfc3030), supported by large inbox providers like Gmail, Outlook.com and iCloud.com.
Chunking makes sending emails more efficient because they don't need to be dot-stuffed and can contain 8 bit data. However, sessions that use chunking no longer delimit requests with CRLF, which makes supporting it harder. I've added a basic extension to James to support chunking so we could have an integration test, but it requires a subclass of its `NettyServer` class to make the Netty channel available.
The new interface on `SmtpSession` is a single method called `sendChunk`. I'll likely refine this as I implement https://github.com/HubSpot/NioSmtpClient/issues/19.

Support chunking

---

src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/EhloResponse.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/messages/ByteBufMessageContent.java
src/main/java/com/hubspot/smtp/messages/CrlfTerminatingChunkedStream.java
src/main/java/com/hubspot/smtp/messages/InputStreamMessageContent.java
src/main/java/com/hubspot/smtp/messages/MessageContent.java
src/main/java/com/hubspot/smtp/messages/MessageContentEncoding.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/EhloResponseTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java
src/test/java/com/hubspot/smtp/messages/ByteBufMessageContentTest.java
src/test/java/com/hubspot/smtp/messages/CrlfTerminatingChunkedStreamTest.java
src/test/java/com/hubspot/smtp/messages/InputStreamMessageContentTest.java
src/test/java/com/hubspot/smtp/messages/MessageContentTest.java

Adds a facade `send(from, to, content)` that sends emails using the most efficient ESTMP extensions as described in https://github.com/HubSpot/NioSmtpClient/issues/19, and adds `RSET` for you if necessary.
Depending on server support and the provided `MessageContent`, `send` might use:
* Pipelining
* Chunking
* 8bitmime
It will automatically dot-stuff messages for you if chunking isn't supported.
A new property on `MessageContent` can describe the message as 7 bit, 8 bit or unknown and the facade uses this to determine the right method to send the message. Messages marked as unknown are sent via chunking or 8bitmime if possible, falling back to an efficient test of the email to see if it contains 8 bit characters.
This PR does not include support for dynamically rewriting 8 bit messages …

Send messages efficiently

---

src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

The type is properly called SSLEngine but the setter ends up
being called sSLEngineSupplier so this naming is nicer.

Correct casing of SslEngineSupplier

---

src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

Updates the `send` facade so it can send to multiple recipients, using pipelining and other ESMTP extensions if possible.
@axiak

Support sending to multiple recipients

---

src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/messages/ByteBufMessageContent.java
src/main/java/com/hubspot/smtp/messages/CrlfTerminatingChunkedStream.java
src/main/java/com/hubspot/smtp/messages/DotStuffingChunkedStream.java
src/main/java/com/hubspot/smtp/messages/InputStreamMessageContent.java
src/main/java/com/hubspot/smtp/messages/MessageContent.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java
src/test/java/com/hubspot/smtp/messages/DotStuffingChunkedStreamTest.java
src/test/java/com/hubspot/smtp/messages/InputStreamMessageContentTest.java
src/test/java/com/hubspot/smtp/messages/MessageContentTest.java

It can be convenient to submit messages based on an `InputStream` without knowing the full size of the stream. Unfortunately though, we rely on knowing the message size in three places:
* to support the ESMTP message size extension (rejecting messages that are over the permitted size)
* to estimate the number of 8 bit characters so we can re-encode messages as quoted-printable or base64 as necessary (in fact re-encoding isn't yet supported)
* to send `BDAT` message chunks
This PR makes the `size` property of `MessageContent` an `OptionalInt` and accommodates the above features as follows:
* we don't check the size of messages where `MessageContent::size` is `OptionalInt.empty()`
* we return a proportion of 8 bit characters (1.0 = all 8 bit; 0.0 = all 7 bit) instead of a count 
* we make …

Make size optional when submitting messages

---

src/main/java/com/hubspot/smtp/TestApp.java
src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

We don't need an `Executor` to be passed to `SmtpSessionFactory` because we can get it from the config.
@axiak

Reuse config executor

---

src/main/java/com/hubspot/smtp/messages/DotStuffing.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java
src/test/java/com/hubspot/smtp/messages/CrlfTerminatingChunkedStreamTest.java
src/test/java/com/hubspot/smtp/messages/DotStuffingChunkedStreamTest.java
src/test/java/com/hubspot/smtp/messages/DotStuffingTest.java

Update tests and the `DotStuffing` class so we don't leak memory. With these changes no leaks are detected in `paranoid` mode, which checks every buffer when it's GC'd.
@axiak

Fix buffer leaks

---

src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java

Makes it possible to override the `Channel` class so that we can use e.g. `EpollSocketChannel` or `NioSocketChannel`.
@axiak

Add a channelClass config

---

src/main/java/com/hubspot/smtp/TestApp.java
src/main/java/com/hubspot/smtp/client/SmtpClientResponse.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

Changes `SmtpClientResponse` so it can hold more than one response. This means we no longer have to deal with arrays of this type and makes client code simpler.
@axiak

Multiple reponses

---

src/main/java/com/hubspot/smtp/client/CompositeSendInterceptor.java
src/main/java/com/hubspot/smtp/client/SendInterceptor.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/test/java/com/hubspot/smtp/client/CompositeSendInterceptorTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

If using a `SendInterceptor` for logging, it's useful to get the full `SmtpRequest` instead of just the command. This PR provides that, and also provides requests sent as part of pipelined sequences.
@axiak

Supply requests when calling interceptors

---

src/main/java/com/hubspot/smtp/utils/SmtpResponses.java
src/test/java/com/hubspot/smtp/utils/SmtpResponsesTest.java

Adds a helper method to format an `SmtpResponse` as a series of lines as it would have been originally received from the remote server.
@axiak

Format responses as a series of lines

---

src/main/java/com/hubspot/smtp/TestApp.java
src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionFactoryConfig.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

This PR moves some configuration options from the `SmtpSession` to the `SmtpSessionFactory` because they relate to all connections.
@axiak

Extract SmtpSessionFactory config

---

src/main/java/com/hubspot/smtp/client/Initializer.java
src/main/java/com/hubspot/smtp/client/ResponseHandler.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java
src/test/java/com/hubspot/smtp/client/ResponseHandlerTest.java

Changes the behaviour of the configured response timeout so it only applies while waiting for a response. The previous behaviour was more like an idle timer and closed connections unnecessarily.
@axiak

Timeout only while waiting for responses

---

src/main/java/com/hubspot/smtp/messages/DotStuffing.java
src/test/java/com/hubspot/smtp/messages/DotStuffingTest.java

Messages that contained a `\r\n` sequence before a `\r\n.\r\n` sequence weren't properly detected, which meant they weren't dot-stuffed.
@axiak

Fix: doesn't dot stuff some messages

---

src/main/java/com/hubspot/smtp/client/CompositeSendInterceptor.java
src/main/java/com/hubspot/smtp/client/EhloResponse.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/test/java/com/hubspot/smtp/client/EhloResponseTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

Sends EHLO after successfully connecting via TLS, as recommended by [the spec](https://tools.ietf.org/html/rfc3207#section-4.2).
@axiak

Ehlo after tls

---

src/main/java/com/hubspot/smtp/messages/DotStuffingChunkedStream.java
src/test/java/com/hubspot/smtp/messages/DotStuffingChunkedStreamTest.java

Fixes a bug where a NullPointerException could be thrown if we asked DotStuffingChunkedStream for a chunk from a closed stream, or one that had already been fully consumed.
@axiak

Fix: end of stream causes NPE

---

src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/ResponseHandler.java
src/test/java/com/hubspot/smtp/client/ResponseHandlerTest.java

Makes the response timeout optional so clients can choose not to use it.
@axiak

Support disabling the response timeout

---

src/main/java/com/hubspot/smtp/messages/InputStreamMessageContent.java
src/test/java/com/hubspot/smtp/messages/InputStreamMessageContentTest.java

Streams that don't support marking were fully consumed while we tried to estimate their 8 bit content, and the error was swallowed. This could lead to us not submitting any content at all, and the session hanging.
This change returns a default (`0.1`) if we can't estimate the 8 bit content. In future, when we support rewriting 8 bit messages to 7 bit, this should mean we use quoted-printable and not base64, which should be appropriate for most messages.
@axiak

Return a fixed estimate when streams cannot mark

---

src/main/java/com/hubspot/smtp/client/EhloResponse.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java

This PR adds support for the `XOAUTH2` authentication mechanism, mainly used by [gmail](https://developers.google.com/gmail/imap/xoauth2-protocol). The code here is pretty simple, and basically just mimicks the existing auth structure, with some added formatting for what gmail expects when using `XOAUTH2`.
I tested this using the `TestApp` and it works! Haven't added any real tests yet though.

Add xoauth2 auth mechanism

---

src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/ResponseHandler.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java
src/test/java/com/hubspot/smtp/client/ResponseHandlerTest.java

Exceptions caught during message sends are returned by completing futures exceptionally, but exceptions encountered outside a send (e.g. a connection closed unexpectedly by the remote host) were not.
This change provides a config option so clients can choose to be notified when connection-level errors occur.

Add exception handler config for connection errors

---

src/main/java/com/hubspot/smtp/client/CompositeSendInterceptor.java

copy-paste error 😢 that led to requests not being logged when pipelining

Fix: interceptor delegates to wrong event

---

src/main/java/com/hubspot/smtp/client/ResponseHandler.java
src/test/java/com/hubspot/smtp/client/ResponseHandlerTest.java

The connection exception handler is useful when it finds exceptions that wouldn't otherwise be detected.
If there is a pending future, this is the best way for clients to handle exceptions.
@axiak

Don't call connection exception handler

---

src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

The `BODY=8BITMIME` parameter [should be sent](https://tools.ietf.org/html/rfc6152#section-2) with the MAIL command, not DATA.
@axiak

Send 8BITMIME parameter with MAIL command, not DATA

---

src/main/java/com/hubspot/smtp/messages/CrlfTerminatingChunkedStream.java
src/test/java/com/hubspot/smtp/messages/CrlfTerminatingChunkedStreamTest.java

Fixes a `NullPointerException` that could be thrown at the end of a stream.
@axiak

Fix: NPE in CrlfTerminatingChunkedStream

---

src/main/java/com/hubspot/smtp/utils/SmtpResponses.java
src/test/java/com/hubspot/smtp/utils/SmtpResponsesTest.java

Sometimes `details()` contains null - this ensures we don't throw when this occurs.

Ignore nulls in SMTP response details

---

src/main/java/com/hubspot/smtp/client/SmtpSession.java

Previously this was run on the executor thread, which meant
there could be a race as two threads tried to replace it
at the same time.

Replace the SmtpRequestEncoder on the IO thread

---

src/main/java/com/hubspot/smtp/client/SmtpSession.java

We've seen some cases where we get a NullPointerException in `getBdatRequestWithData` suggesting `firstChunk` is null, which will happen if there is no readable content.

Throw an exception if the MessageContent could not be read

---

src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

If a server responds with a very small maximum message size, it's likely to be an error. We should try anyway in these cases rather than refusing to send the message.
@axiak

Ignore max message size less than 1k

---

src/main/java/com/hubspot/smtp/client/EhloResponse.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/test/java/com/hubspot/smtp/client/EhloResponseTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

The SIZE spec specifically calls out size '0' as indicating that no size limits are in effect. We haven't seen any other bad values in the wild, so replacing the validity threshold with this is better.
@axiak

Ignore SIZE 0 in the EHLO response

---

src/main/java/com/hubspot/smtp/client/KeepAliveHandler.java
src/main/java/com/hubspot/smtp/client/ResponseHandler.java
src/test/java/com/hubspot/smtp/client/KeepAliveHandlerTest.java
src/test/java/com/hubspot/smtp/client/ResponseHandlerTest.java

If this message is logged, it's likely because something has timed out; understanding what will help to troubleshoot.
@axiak

Log the response we're waiting for in KeepAliveHandler

---

src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/ResponseHandler.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java
src/test/java/com/hubspot/smtp/client/ResponseHandlerTest.java

If we successfully connect via TCP, but the server doesn't respond,
we should time out and ensure the connection is closed. Previously,
the connect future would complete exceptionally but the channel
would remain open, along with its KeepAliveHandler if configured.
We use a separate timeout here because clients might reasonably
expect servers to respond quicker to the initial connection
compared to, e.g., a DATA command.

Close the connection if the remote server doesn't respond

---

pom.xml
src/main/java/com/hubspot/smtp/client/DotCrlfBuffer.java
src/main/java/com/hubspot/smtp/client/Extension.java
src/main/java/com/hubspot/smtp/client/Initializer.java
src/main/java/com/hubspot/smtp/client/SmtpSession.java
src/main/java/com/hubspot/smtp/client/Utf8SmtpRequestEncoder.java
src/main/java/com/hubspot/smtp/client/Utf8SmtpResponseDecoder.java
src/test/java/com/hubspot/smtp/client/EhloResponseTest.java
src/test/java/com/hubspot/smtp/client/SmtpSessionTest.java

Adds support for SMTPUTF8 ([rfc](https://tools.ietf.org/html/rfc6531)).
If supported is detected in the EHLO response and the sender or recipients' addresses contain unicode characters, the SMTPUTF8 parameter is sent with the MAIL command.
Netty's SmtpRequestEncoder and SmtpResponseDecoder render and parse parameters as ASCII, so these were copied into this project and changed slightly. 
@axiak @kevinwbaker

Support SMTPUTF8

---

src/main/java/com/hubspot/smtp/client/ResponseCollector.java
src/main/java/com/hubspot/smtp/client/ResponseException.java
src/test/java/com/hubspot/smtp/client/ResponseHandlerTest.java

If a server is using pipelining we may have already
received valid responses before a connection is closed.
To help debugging, we should include details of any
received responses when throwing an exception.
@kevinwbaker

Include response details when we handle an exception

---

src/main/java/com/hubspot/smtp/client/AbstractSmtpSessionConfig.java
src/main/java/com/hubspot/smtp/client/SmtpSessionFactory.java

When we connect to an SMTP server, we wait for two events: the initial TCP
connection completing (from the client's point of view, this is the
arrival of the SYN/ACK from the remote server) and receiving the initial
SMTP message (e.g. "220 OK").
Users of this library however, aren't able to do much with this
distinction. There's nothing productive to do until the initial response
is received, so that is the only timeout that really matters.
Futhermore, there was a bug in the previous implementation: if you set a
lower initialResponseReadTimeout than connectionTimeout, the client would
always see a failure even if the TCP connection was established.
Instead, we simplify the API by adding initialResponseTimeout.
This applies to the time from the initial SYN sent from the client to
the …

Simplify connect and initial response read timeouts

---

pom.xml
src/test/java/com/hubspot/smtp/IntegrationTest.java
src/test/java/com/hubspot/smtp/client/KeepAliveHandlerTest.java

basepom 59.10 upgrades netty from 4.1.8 to 4.1.110.
`IntegrationTest` fails with the upgrade, with the error:
```
javax.net.ssl.SSLException: Received fatal alert: internal_error
```
which was wrapping this error:
```
No supported CertificateVerify signature algorithm for RSA  key
```
I believe this is due to default protocol changing to [`TLSv1.3`](https://github.com/netty/netty/commit/b1d3aad404a39143da7a86c121d60f35c0d21108), and the effect it as on the fixture cert used in the test.

upgrade netty to 4.1.110
